version: '3'

services:
  ubuntu-container:
    image: ubuntu
    container_name: ubuntu-container
    networks:
      - Hamar-utvikling
    stdin_open: true
    tty: true
    command: /bin/bash

networks:
  Hamar-utvikling:
    external: true